import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

// Replace these two values with the Project URL and anon public key from Supabase.
const SUPABASE_URL = "PASTE_YOUR_SUPABASE_URL_HERE";
const SUPABASE_ANON_KEY = "PASTE_YOUR_SUPABASE_ANON_KEY_HERE";
const sb=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const DEMO_USERS={username:"1234",Josephine:"1234",Boss:"1234",Staff:"1234"};
let vehicles=[],expenses=[],petty=[],requisitions=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function money(n){return "KSh "+Number(n||0).toLocaleString("en-KE",{maximumFractionDigits:0})}
function start(){ $("loginMsg").textContent=""; }
$("loginForm").onsubmit=async e=>{e.preventDefault();const u=$("username").value.trim(),pass=$("password").value;if(DEMO_USERS[u]!==pass){$("loginMsg").textContent="Incorrect username or password.";return}$("login").classList.add("hidden");$("app").classList.remove("hidden");$("today").textContent=new Date().toLocaleDateString("en-KE",{day:"numeric",month:"long",year:"numeric"});await load();showPage("dashboard")};
$("logout").onclick=()=>{$("app").classList.add("hidden");$("login").classList.remove("hidden")};
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));
function showPage(name){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active-page"));$(name)?.classList.add("active-page");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===name));if(name==="vehicles")renderVehicles();if(name==="expenses")renderExpensePage();if(name==="petty")renderPetty();if(name==="requisitions")renderReq();}
async function load(){
 const results=await Promise.all([sb.from("vehicles").select("*").order("created_at",{ascending:false}),sb.from("expenses").select("*").order("expense_date",{ascending:false}),sb.from("petty_cash").select("*").order("cash_date",{ascending:false}),sb.from("requisitions").select("*").order("req_date",{ascending:false})]);
 vehicles=results[0].data||[];expenses=results[1].data||[];petty=results[2].data||[];requisitions=results[3].data||[];renderDashboard();renderVehicles();renderExpensePage();renderPetty();renderReq();
}
function renderDashboard(){
 const totalExp=expenses.reduce((a,e)=>a+Number(e.amount||0),0),cash=petty.reduce((a,e)=>a+(e.category==="Income"?-Number(e.amount||0):Number(e.amount||0)),0),pending=requisitions.filter(r=>String(r.status||"").toLowerCase()==="pending").length||requisitions.length;
 const repair=vehicles.filter(v=>v.status==="Under Repair").length,active=vehicles.filter(v=>["Completed","Released"].includes(v.status)).length,storage=vehicles.filter(v=>v.status==="Storage").length;
 $("dashVehicles").textContent=vehicles.length;$("dashActive").textContent=active;$("dashRepair").textContent=repair;$("dashExpenses").textContent=money(totalExp);$("dashPetty").textContent=money(cash);$("dashReq").textContent=pending;$("donutTotal").textContent=vehicles.length;$("activeLegend").textContent=active;$("repairLegend").textContent=repair;$("outLegend").textContent=storage;$("reportExpenses").textContent=money(totalExp);$("reportFleet").textContent=vehicles.length;$("reportPetty").textContent=money(cash);$("reportReq").textContent=pending;$("pettyPage").textContent=money(cash);
 const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],vals=months.map((_,i)=>expenses.filter(e=>new Date(e.expense_date||e.created_at||Date.now()).getMonth()===i).reduce((a,e)=>a+Number(e.amount||0),0)),max=Math.max(...vals,1);$("expenseChart").innerHTML=vals.map((v,i)=>`<div class="bar" style="height:${Math.max(12,v/max*100)}%"><label>${months[i]}</label></div>`).join("");
 $("donut").style.background=`conic-gradient(#16a36a 0 ${vehicles.length?active/vehicles.length*100:0}%,#f79009 ${vehicles.length?active/vehicles.length*100:0}% ${vehicles.length?(active+repair)/vehicles.length*100:100}%,#ef4444 ${vehicles.length?(active+repair)/vehicles.length*100:0}% 100%)`;
 const recent=[...expenses.slice(0,3).map(e=>({icon:"◈",text:`Expense — ${e.description||"Garage expense"}`,amount:money(e.amount)})),...requisitions.slice(0,2).map(r=>({icon:"▤",text:`Requisition — ${r.req_no||"Request"}`,amount:r.status||"Pending"}))].slice(0,4);$("activityList").innerHTML=recent.length?recent.map(a=>`<div class="activity-row"><span class="activity-icon">${a.icon}</span><b>${esc(a.text)}</b><small>${esc(a.amount)}</small></div>`).join(""):`<p class="muted">No recent activity.</p>`;
}
function renderVehicles(){if(!$('list'))return;const q=($('search')?.value||'').toLowerCase(),f=$('filter')?.value||'';const rows=vehicles.filter(v=>(!q||String(v.registration).toLowerCase().includes(q)||String(v.customer).toLowerCase().includes(q))&&(!f||v.status===f));$('list').innerHTML=rows.length?rows.map(card).join(""):`<p class="muted">No vehicles found.</p>`}
function card(v){const es=expenses.filter(e=>e.vehicle_id===v.id),cost=es.reduce((a,e)=>a+Number(e.amount||0),0),bal=Math.max(0,Number(v.billed||0)-Number(v.paid||0));return `<article class="vehicle"><div class="vehicle-top"><div><h3>${esc(v.registration)}</h3><span class="muted">${esc(v.customer)} • ${esc(v.date_in)}</span></div><span class="badge">${esc(v.status)}</span></div><p class="muted">${esc(v.description||"No description")}</p><div class="grid"><div><small>Expenses</small><b>${money(cost)}</b></div><div><small>Charge-out</small><b>${money(v.billed)}</b></div><div><small>Paid</small><b>${money(v.paid)}</b></div><div><small>Balance</small><b>${money(bal)}</b></div></div><div class="actions"><button onclick="expense('${v.id}')">+ Expense</button><button class="secondary" onclick="edit('${v.id}')">Edit</button><button class="secondary" onclick="removeVehicle('${v.id}')">Delete</button></div></article>`}
function renderExpensePage(){const total=expenses.reduce((a,e)=>a+Number(e.amount||0),0);$("expenseTotalPage").textContent=money(total);$("expenseTable").innerHTML=expenses.slice(0,12).map(e=>`<div class="expense-row"><span>${esc(e.expense_date)} — ${esc(e.description||"")}</span><b>${money(e.amount)}</b></div>`).join("")||`<p class="muted">No expenses recorded.</p>`}
function renderPetty(){$("pettyTable").innerHTML=petty.slice(0,12).map(e=>`<div class="expense-row"><span>${esc(e.cash_date)} — ${esc(e.description||"")}</span><b>${money(e.amount)}</b></div>`).join("")||`<p class="muted">No petty cash records.</p>`}
function renderReq(){$("reqTable").innerHTML=requisitions.slice(0,12).map(r=>`<div class="expense-row"><span>${esc(r.req_no||"")} — ${esc(r.item_description||"")}</span><b>${esc(r.status||"Pending")}</b></div>`).join("")||`<p class="muted">No requisitions found.</p>`}
$("addVehicle").onclick=()=>openVehicle();document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add("hidden"));
function openVehicle(v=null){$("vTitle").textContent=v?"Edit Vehicle":"Add Vehicle";$("vid").value=v?.id||"";$("reg").value=v?.registration||"";$("customer").value=v?.customer||"";$("date_in").value=v?.date_in||new Date().toISOString().slice(0,10);$("job_type").value=v?.job_type||"Repair";$("status").value=v?.status||"Under Repair";$("description").value=v?.description||"";$("billed").value=v?.billed||0;$("paid").value=v?.paid||0;$("vehicleModal").classList.remove("hidden")}
$("vehicleForm").onsubmit=async e=>{e.preventDefault();let id=$("vid").value,data={registration:$("reg").value.trim().toUpperCase(),customer:$("customer").value.trim(),date_in:$("date_in").value,job_type:$("job_type").value,status:$("status").value,description:$("description").value,billed:Number($("billed").value),paid:Number($("paid").value)};let r=id?await sb.from("vehicles").update(data).eq("id",id):await sb.from("vehicles").insert(data);if(r.error)return toast(r.error.message);$("vehicleModal").classList.add("hidden");await load();toast("Vehicle saved")};
window.edit=id=>openVehicle(vehicles.find(v=>v.id===id));window.removeVehicle=async id=>{if(!confirm("Delete this vehicle?"))return;let r=await sb.from("vehicles").delete().eq("id",id);if(r.error)return toast(r.error.message);await load();toast("Vehicle deleted")};window.expense=id=>{$("evid").value=id;$('edate').value=new Date().toISOString().slice(0,10);$("edesc").value="";$("eamount").value="";$("expenseModal").classList.remove("hidden")};$("expenseForm").onsubmit=async e=>{e.preventDefault();let r=await sb.from("expenses").insert({vehicle_id:$("evid").value,expense_date:$("edate").value,description:$("edesc").value,category:$("ecat").value,amount:Number($("eamount").value)});if(r.error)return toast(r.error.message);$("expenseModal").classList.add("hidden");await load();toast("Expense saved")};$("search").oninput=renderVehicles;$("filter").onchange=renderVehicles;function toast(t){$("toast").textContent=t;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2000)}start();
